spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_platform_db
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  application:
    name: LearningPlatform



